qiime2/q2-emperor

q2_emperor/plugin_setup.py

With the recent updates to the Emperor API, the copy and creation of the
HTML plot can now be done in two separate steps. Without the need of
doing a string replacement over the entire HTML plot.
For more info, see this PR:
https://github.com/biocore/emperor/pull/511

ENH: Remove hack

---

q2_emperor/plugin_setup.py
setup.py

**NOT READY FOR MERGE**
@ElDeveloper, can you confirm this information?

ENH: adds citation and user support text

---

q2_emperor/plugin_setup.py

fixed custom-axis bug and updated parameter name for consistency with other plugins

BUG/MAINT: fixed custom-axis bug/updated parameter name

---

q2_emperor/__init__.py
setup.py

Revert "MAINT: Bump to dev version"

---

.travis.yml
q2_emperor/tests/__init__.py

TST: Add Travis/Tests

---

ci/recipe/meta.yaml

This reverts commit a43eec54ffdadb64d67c71cf3e62b47d951c3220.

Revert "BLD: Update to beta-9 (#46)"

---

ci/recipe/meta.yaml
q2_emperor/tests/test_plot.py

And update version dependency.

Fix test that initializes eigenvalues to array instead of 🐼 series

---

ci/recipe/meta.yaml

This is waiting on the conda-forge builds here:
https://github.com/conda-forge/emperor-feedstock/commits/master
~~https://github.com/conda-forge/emperor-feedstock/pull/11~~

BLD: Bump release to beta 10

---

ci/recipe/meta.yaml

Dependent on this patch:
https://github.com/conda-forge/emperor-feedstock/commits/master

BLD: Bump Emperor version

---

ci/recipe/meta.yaml
q2_emperor/plugin_setup.py

~~Depends on the conda-forge build here:~~
~~https://github.com/conda-forge/emperor-feedstock/pull/13~~
~~https://travis-ci.org/conda-forge/emperor-feedstock/builds/304925259~~
Build is ready.

BLD: Update dependency to beta-12 and add citation

---

q2_emperor/plugin_setup.py
q2_emperor/tests/test_plot.py

See qiime2/qiime2#359 for details.

MAINT: new metadata updates

---

q2_emperor/_plot.py
q2_emperor/plugin_setup.py
q2_emperor/tests/test_plot.py

Users can now provide more than one custom axis.
Fixes #54

ENH: Support varidic arguments as custom_axes

---

ci/recipe/meta.yaml

Includes a number of bug fixes.
Fixes #50

BLD: Update to beta14

---

ci/recipe/meta.yaml

REL: Update to beta16

---

q2_emperor/_plot.py
q2_emperor/plugin_setup.py

Added ignore_missing_samples parameter to the plot, biplot and procrustes_plot, addressing #64 
I've tested it out, it works - let me know if you have comments.  Thanks!

ENH: Adding in ignore_missing_samples parameter

---

ci/recipe/meta.yaml

Pending the conda-forge build finishes:
https://github.com/conda-forge/emperor-feedstock/pull/21

BLD: Bump to newer version of Emperor

---

q2_emperor/plugin_setup.py

The purpose of this PR is to update the help text for emperor biplot. See issue #79

MAINT: Initial commit to update the help text for biplot

---

LICENSE
q2_emperor/__init__.py
q2_emperor/_plot.py
q2_emperor/plugin_setup.py
q2_emperor/tests/__init__.py
q2_emperor/tests/test_plot.py
q2_emperor/tests/test_plugin_setup.py
setup.py

Updated copyright headers to reflect current year.

MAINT: Update copyright headers to 2020

---

q2_emperor/_plot.py
q2_emperor/plugin_setup.py
q2_emperor/tests/test_plot.py

Biplot arrows are now ignored in the plot method.

ENH: Remove features and show warning in plot

---

.github/workflows/ci.yml
ci/recipe/meta.yaml

Bumps dependency version to 1.0.3, depends on the following PR being merged and creating a new release:
biocore/emperor#799

Update to the latest EMPeror version 🐧
